<?php
// this entire script is a hack lmao

$version = $_SERVER['devilfishGitRev'] ?? "unknown";
$tpl = file_get_contents("export-tiles/map.tpl.html");

$tpl = str_replace(
  "Generated by TilesXYZ", 
  'devilfish.qgs // renderTiles.ps1 | tag <a href="https://github.com/sylae/devilfish-map" target="_blank">'.$version.'</a> | '.date(DATE_ATOM),
  $tpl
);
$tpl = str_replace(
  "Leaflet Preview", 
  'Devilfish, Minnesota',
  $tpl
);

$local = str_replace("file:///export-tiles", ".", $tpl);
$cdn = str_replace("file:///export-tiles", "https://cdn.syl.ae/wormrp/map", $tpl);

file_put_contents("export-tiles/map.local.html", $local);
file_put_contents("export-tiles/map.cdn.html", $cdn);
